// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzGCXWgNH8NCn1uAf8mg8qxHP5UmG9lTI',
    appId: '1:915956392136:web:66042e0abf4056118b05fd',
    messagingSenderId: '915956392136',
    projectId: 'only-for-me-5392',
    authDomain: 'only-for-me-5392.firebaseapp.com',
    databaseURL: 'https://only-for-me-5392-default-rtdb.firebaseio.com',
    storageBucket: 'only-for-me-5392.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI_A23CMf5OHOhCQFCzN-djWJYdMsGSso',
    appId: '1:915956392136:android:19f1ee9b289d12bd8b05fd',
    messagingSenderId: '915956392136',
    projectId: 'only-for-me-5392',
    databaseURL: 'https://only-for-me-5392-default-rtdb.firebaseio.com',
    storageBucket: 'only-for-me-5392.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3LTC11TsZQO2YXC8e930yMfTCQ4yzZw8',
    appId: '1:915956392136:ios:65c495f0c5aa040b8b05fd',
    messagingSenderId: '915956392136',
    projectId: 'only-for-me-5392',
    databaseURL: 'https://only-for-me-5392-default-rtdb.firebaseio.com',
    storageBucket: 'only-for-me-5392.appspot.com',
    androidClientId:
        '915956392136-egtp7gegub14duspubh09k123fue465h.apps.googleusercontent.com',
    iosClientId:
        '915956392136-0m88ge2o10o7bsq9950gkilll7jn8nfm.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlyForMe',
  );
}
